# action.yml
name: "GPG key import"
description: "Import private GPG key"
runs:
  using: "composite"
  steps:
    - id: set-default-cache-ttl
      run: |
        gpg-agent --daemon --default-cache-ttl 7200
      shell: bash
      name: set default cache ttl
    - run: |
        #
        echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "${{ env.PASSPHRASE }}" temp.txt
        rm temp.txt
      shell: bash
      name: import GPG key and prime passphrase
    - id: gpg-key
      run: |
        keyid=$(gpg --with-colons --list-keys | awk -F: '/^pub/ { print $5 }')
        armor=$(gpg --armor --export ${keyid} | sed -e ':a;N;$!ba;s/\n/\\n/g')
        echo "::set-output name=keyid::$keyid"
        echo "::set-output name=armor::$armor"
      shell: bash
      name: set gpg key output

outputs:
  keyid:
    description: "KeyID of the GPG key"
    value: ${{ steps.gpg-key.outputs.keyid }}
  pub_ascii_armor:
    description: "Armored version of the Public GPG key"
    value: ${{ steps.gpg-key.outputs.armor }}
